services:
  db:
    image: postgres:16
    container_name: maebanjumpen-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: maebanjumpen
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d maebanjumpen"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - maebanjumpen-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maebanjumpen-app
    ports:
      - "8088:8088"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/maebanjumpen
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
    networks:
      - maebanjumpen-network
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./qr_codes:/app/qr_codes

networks:
  maebanjumpen-network:
    driver: bridge

volumes:
  postgres-data: