services:
  db:
    image: mysql:8.0
    container_name: maebanjumpen-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: maebanjumpen
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - maebanjumpen-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maebanjumpen-app
    ports:
      - "8088:8088"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/maebanjumpen?characterEncoding=UTF-8&serverTimezone=Asia/Bangkok&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
    networks:
      - maebanjumpen-network
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./qr_codes:/app/qr_codes

networks:
  maebanjumpen-network:
    driver: bridge

volumes:
  mysql-data: